# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.1"

# Sinatra for the HTTP endpoint; rackup + puma to serve it.
gem "sinatra", "~> 4.0"
gem "rackup", "~> 2.1"
gem "puma", "~> 6.4"
